<!doctype html>

<html lang="es">
	<head>
		<title>News123 Portal de noticias</title>
		<meta charset="utf-8">
		<link href='http://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>

		<link rel="stylesheet" type="text/css" href="/css/styles.css" >

		<script src="/js/scripts.js" type="text/javascript" ></script>
	</head>

	<body>

		<header>
			<hgroup>
				<h1>News 123 portal de noticias con Zend Framework</h1>
			</hgroup>

			<nav>
				<ul>
					<li><a href="/">Inicio</a></li>
					<li><a href="/mundo/hola">Hola</a></li>
					<li><a href="/mundo/chau">Chau</a></li>
				</ul>
			</nav>
		</header>




		<section>

			<?php echo $this->layout()->content ?>

		</section>

		<footer>
			<p>Portal de noticias desarrollado con Zend Framework</p>
		</footer>
	</body>
</html>

